dataset_root: "/workspace/ViInfographicVQA"
data_mode: "single" # ""single, "multi", "single_and_multi" 
use_subdataset: false
# Bật: loại mẫu có câu trả lời (sau normalize) dài hơn 20 token tách bằng khoảng trắng. Tắt: giữ mọi mẫu.
filter_answers_over_20_tokens: false

adapter_out_dir: "checkpoints/lora_adapters"

model_id: "Qwen/Qwen2.5-VL-7B-Instruct"
system_prompt: "Answer the following question based solely on the image content concisely with a single term."
attn_implementation: "flash_attention_2"

min_pixels: 200704
max_pixels: 1003520

seed: 42
epochs: 3
batch_size: 16 # for H100
grad_accum: 8
lr: 0.0002

lora_r: 16
lora_alpha: 32
lora_dropout: 0.05

save_steps: 100
save_total_limit: 3
logging_steps: 10
max_seq_length: 1024

use_wandb: true
wandb_env_file: "ft-qwen/.wandb.env"
wandb_project: "vqa-qlora"
wandb_entity: dla-hcmut # team's entity
wandb_group: "qwen-finetune"
wandb_job_type: "train"
wandb_run_name: null
wandb_notes: null
wandb_mode: "online"
wandb_tags:
  - "qwen2.5-vl"
  - "viinfographicvqa"
  - "qlora"
wandb_save_code: true
wandb_log_artifacts: true
wandb_log_final_checkpoint: true

bf16: true
load_in_4bit: true
bnb_4bit_use_double_quant: true
bnb_4bit_quant_type: "nf4"
bnb_4bit_compute_dtype: "bfloat16"

dataloader_num_workers: 4
pin_memory: true
persistent_workers: true
